In [9]:
import numpy as np


def lu_basic(A):
    n = A.shape[0]  
    L = np.eye(n)   
    U = np.zeros((n, n))  

    for j in range(n):  # Pro každý sloupec
        if j == 0:
            v = A[j:, j]  # První sloupec se bere přímo z A
        else:
            # Řešíme systém L * z = A[:, j] pro horní část
            z = np.linalg.solve(L[0:j, 0:j], A[0:j, j])
            U[0:j, j] = z  # Uložení výsledku do horní části U
            v = A[j:, j] - L[j:, 0:j] @ z  # Zbytek sloupce (spodní část)

        if j < n - 1:
            # Výpočet prvků pod diagonálou do L
            L[j+1:n, j] = v[1:] / v[0]

        U[j, j] = v[0]  # Diagonální prvek U

    return L, U


A = np.array([[2.0, 1.0, 1.0],
              [4.0, -6.0, 0.0],
              [-2.0, 7.0, 2.0]])

L, U = lu_basic(A)
print("Basic LU decomposition:")
print("A =\n", A)
print("L =\n", L)
print("U =\n", U)
print("A - LU =\n", A - L @ U)

Basic LU decomposition:
A =
 [[ 2.  1.  1.]
 [ 4. -6.  0.]
 [-2.  7.  2.]]
L =
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1. -1.  1.]]
U =
 [[ 2.  1.  1.]
 [ 0. -8. -2.]
 [ 0.  0.  1.]]
A - LU =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
def lu_general(A):
    m, n = A.shape
    L = np.eye(m)
    U = np.zeros((m, n))

    for j in range(n):
        if j == 0:
            v = A[j:, j]
        else:
            # Horní část sloupce U
            z = np.linalg.solve(L[0:j, 0:j], A[0:j, j])
            U[0:j, j] = z

            # Spodní část vektoru v
            v = A[j:, j] - L[j:, 0:j] @ z

        

        # Do L zapisujeme hodnoty pod diagonálou
        if j < m - 1:
            L[j+1:m, j] = v[1:] / v[0]

        # Diagonální prvek U
        U[j, j] = v[0]

    return L, U

"""
A = np.array([
    [1,  -1,  0,  2],
    [0,  1,  0,  1],
    [1,  0,  -1,  0],
    [-1,  2,  1,  -1],
    [0, 1, 0,  1],
    [0, 0, 2,  0]
], dtype=float)
"""

A = np.array([
    [2,  1,  0,  0],
    [4,  3,  1,  0],
    [6,  5,  3,  1],
    [8,  7,  5,  3],
    [10, 9,  7,  5],
    [12, 11, 9,  7]
], dtype=float)

L, U = lu_general(A)
print("General LU decomposition:")
print("A =\n", A)
print("L = \n", L)
print("U = \n", U)
print("A - LU = \n", A - L @ U)

General LU decomposition:
A =
 [[ 2.  1.  0.  0.]
 [ 4.  3.  1.  0.]
 [ 6.  5.  3.  1.]
 [ 8.  7.  5.  3.]
 [10.  9.  7.  5.]
 [12. 11.  9.  7.]]
L = 
 [[1. 0. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0. 0.]
 [3. 2. 1. 0. 0. 0.]
 [4. 3. 2. 1. 0. 0.]
 [5. 4. 3. 2. 1. 0.]
 [6. 5. 4. 3. 0. 1.]]
U = 
 [[ 2.  1.  0.  0.]
 [ 0.  1.  1. -0.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
A - LU = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
